class ConfigError(Exception):
    """Raise an error if there are problems using data from djmpc_config.py"""
    pass
